name: Generate Daily Playlist

on:
  schedule:
    - cron: '0 4 * * *' # Runs at 4am UTC (1am UK time) every day
  workflow_dispatch: # Allows to manually trigger the workflow from the GitHub Actions page

permissions:
  contents: write

jobs:
  remove-previous-playlist:
    runs-on: ubuntu-latest
    environment: suggest_env
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install spotipy python-dotenv

    - name: Debug - List Playlists
      env:
        SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
        SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
        SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
      run: |
        python -c "
        import spotipy
        from spotipy.oauth2 import SpotifyOAuth
        import os

        sp = spotipy.Spotify(auth_manager=SpotifyOAuth(
            client_id=os.getenv('SPOTIFY_CLIENT_ID'),
            client_secret=os.getenv('SPOTIFY_CLIENT_SECRET'),
            redirect_uri='http://localhost:8888/callback',
            scope='playlist-read-private playlist-modify-private playlist-modify-public'
        ))

        playlists = sp.current_user_playlists()
        for playlist in playlists['items']:
            print(f'Playlist: {playlist['name']}')
        "

    - name: Remove previous day's playlist
      env:
        SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
        SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
        SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
      run: |
        python remove_previous_playlist.py

  generate-recommendations:
    needs: remove-previous-playlist
    runs-on: ubuntu-latest
    environment: suggest_env
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
  
    
    - name: Run Spotify recommendation script
      env:
        SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
        SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
        SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        python suggest_spotify.py

    - name: Checkout and update docs-suggestions-md branch
      run: |
        git fetch origin
        git checkout -B docs-suggestions-md origin/docs-suggestions-md || git checkout -b docs-suggestions-md
        git pull origin docs-suggestions-md --rebase || true
        
    - name: Commit and push changes to docs-suggestions-md branch
      run: |
        git config user.name 'GitHub Action'
        git config user.email 'action@github.com'
        git add DailyRecsMarkdown/*.md
        git commit -m "Update Spotify recommendations for $(date +'%Y-%m-%d')" || echo "No changes to commit"
        git push --force origin docs-suggestions-md
