name: Generate Daily Playlist

on:
  schedule:
    - cron: '0 4 * * *' # Runs at 4am UTC (1am UK time) every day
  workflow_dispatch: # Allows to manually trigger the workflow from the GitHub Actions page

jobs:
  generate-recommendations:
    runs-on: ubuntu-latest
    environment: suggest_env
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run Spotify recommendation script
      env:
        SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
        SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python suggest_spotify.py
    
    - name: Commit and push if changes
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add DailyRecsMarkdown/*.md
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update Spotify recommendations" && git push)
